export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST"
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS"
export const CREATE_STORE_FAILURE = "CREATE_STORE_FAILURE"

export const GET_ALL_STORES_REQUEST = "GET_ALL_STORES_REQUEST"
export const GET_ALL_STORES_SUCCESS = "GET_ALL_STORES_SUCCESS"
export const GET_ALL_STORES_FAILURE = "GET_ALL_STORES_FAILURE"

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST"
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS"
export const DELETE_STORE_FAILURE = "DELETE_STORE_FAILURE"

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST"
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS"
export const UPDATE_STORE_FAILURE = "UPDATE_STORE_FAILURE"

export const GET_STORE_BY_ID_REQUEST = "GET_STORE_BY_ID_REQUEST"
export const GET_STORE_BY_ID_SUCCESS = "GET_STORE_BY_ID_SUCCESS"
export const GET_STORE_BY_ID_FAILURE = "GET_STORE_BY_ID_FAILURE"

export const GET_STORE_BY_USER_ID_REQUEST = "GET_STORE_BY_USER_ID_REQUEST"
export const GET_STORE_BY_USER_ID_SUCCESS = "GET_STORE_BY_USER_ID_SUCCESS"
export const GET_STORE_BY_USER_ID_FAILURE = "GET_STORE_BY_USER_ID_FAILURE"

export const UPDATE_STORE_STATUS_REQUEST = "UPDATE_STORE_STATUS_REQUEST"
export const UPDATE_STORE_STATUS_SUCCESS = "UPDATE_STORE_STATUS_SUCCESS"
export const UPDATE_STORE_STATUS_FAILURE = "UPDATE_STORE_STATUS_FAILURE"

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST"
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS"
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE"


export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST"
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS"
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE"

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST"
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS"
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE"

export const GET_STORES_EVENTS_REQUEST = "GET_STORES_EVENTS_REQUEST"
export const GET_STORES_EVENTS_SUCCESS = "GET_STORES_EVENTS_SUCCESS"
export const GET_STORES_EVENTS_FAILURE = "GET_STORES_EVENTS_FAILURE"

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST"
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"

export const GET_STORES_CATEGORY_REQUEST = "GET_STORES_CATEGORY_REQUEST"
export const GET_STORES_CATEGORY_SUCCESS = "GET_STORES_CATEGORY_SUCCESS"
export const GET_STORES_CATEGORY_FAILURE = "GET_STORES_CATEGORY_FAILURE"